#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_PlayerCameraModeRanged_FireworksMortar

#include "Basic.hpp"

#include "Athena_PlayerCameraModeLauncherMilitary_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_PlayerCameraModeRanged_FireworksMortar.Athena_PlayerCameraModeRanged_FireworksMortar_C
// 0x0000 (0x0CF0 - 0x0CF0)
class UAthena_PlayerCameraModeRanged_FireworksMortar_C final : public UAthena_PlayerCameraModeLauncherMilitary_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Athena_PlayerCameraModeRanged_FireworksMortar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Athena_PlayerCameraModeRanged_FireworksMortar_C")
	}
	static class UAthena_PlayerCameraModeRanged_FireworksMortar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_PlayerCameraModeRanged_FireworksMortar_C>();
	}
};
DUMPER7_ASSERTS_UAthena_PlayerCameraModeRanged_FireworksMortar_C;

}

