#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_Prop_Prop_Bear

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_Prop_Prop_Bear.Athena_Prop_Prop_Bear_C
// 0x0010 (0x0B20 - 0x0B10)
class AAthena_Prop_Prop_Bear_C final : public ABuildingProp
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0B10(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          Effects;                                           // 0x0B18(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)

public:
	void ExecuteUbergraph_Athena_Prop_Prop_Bear(int32 EntryPoint);
	void OnDeathServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Athena_Prop_Prop_Bear_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Athena_Prop_Prop_Bear_C")
	}
	static class AAthena_Prop_Prop_Bear_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthena_Prop_Prop_Bear_C>();
	}
};
DUMPER7_ASSERTS_AAthena_Prop_Prop_Bear_C;

}

