#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_GameMode

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_GameMode.Athena_GameMode_C
// 0x0008 (0x1248 - 0x1240)
class AAthena_GameMode_C final : public AFortGameModeAthena
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x1240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Athena_GameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Athena_GameMode_C")
	}
	static class AAthena_GameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthena_GameMode_C>();
	}
};
DUMPER7_ASSERTS_AAthena_GameMode_C;

}

