#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_Tree_Medium_03_

#include "Basic.hpp"

#include "Parent_Tree_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_Tree_Medium_03_.Athena_Tree_Medium_03__C
// 0x0000 (0x0BD0 - 0x0BD0)
class AAthena_Tree_Medium_03__C final : public AParent_Tree_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Athena_Tree_Medium_03__C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Athena_Tree_Medium_03__C")
	}
	static class AAthena_Tree_Medium_03__C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthena_Tree_Medium_03__C>();
	}
};
DUMPER7_ASSERTS_AAthena_Tree_Medium_03__C;

}

