#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Pistol_Flintlock_Athena

#include "Basic.hpp"

#include "B_Pistol_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Pistol_Flintlock_Athena.B_Pistol_Flintlock_Athena_C
// 0x0018 (0x0DC0 - 0x0DA8)
class AB_Pistol_Flintlock_Athena_C final : public AB_Pistol_Generic_C
{
public:
	class UStaticMeshComponent*                   Flintlock_SingleShot_Powder_Top;                   // 0x0DA8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Flintlock_SingleShot_Powder_bottom;                // 0x0DB0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Flintlock_SingleShot_Ram;                          // 0x0DB8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_Pistol_Flintlock_Athena_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_Pistol_Flintlock_Athena_C")
	}
	static class AB_Pistol_Flintlock_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Pistol_Flintlock_Athena_C>();
	}
};
DUMPER7_ASSERTS_AB_Pistol_Flintlock_Athena_C;

}

