#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Athena_SmokeBomb

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "B_Prj_Athena_Grenade_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Prj_Athena_SmokeBomb.B_Prj_Athena_SmokeBomb_C
// 0x0020 (0x0778 - 0x0758)
class AB_Prj_Athena_SmokeBomb_C final : public AB_Prj_Athena_Grenade_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_Prj_Athena_SmokeBomb_C;           // 0x0758(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               ParticleSystem;                                    // 0x0760(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0768(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        P_SmokeGrenadeExplosion;                           // 0x0770(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_Prj_Athena_SmokeBomb(int32 EntryPoint);
	void FailsafeTimer();
	void ReceiveBeginPlay();
	void FuseEnded();
	void BndEvt__OverlapCapsule_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void OnExploded(const TArray<class AActor*>& HitActors, const TArray<struct FHitResult>& HitResults);
	void OnBounce(const struct FHitResult& Hit);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_Prj_Athena_SmokeBomb_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_Prj_Athena_SmokeBomb_C")
	}
	static class AB_Prj_Athena_SmokeBomb_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Prj_Athena_SmokeBomb_C>();
	}
};
DUMPER7_ASSERTS_AB_Prj_Athena_SmokeBomb_C;

}

