#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_ShadowBomb_Athena

#include "Basic.hpp"

#include "B_ConsumableSmall_Athena_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_ShadowBomb_Athena.B_ShadowBomb_Athena_C
// 0x0028 (0x0950 - 0x0928)
class AB_ShadowBomb_Athena_C final : public AB_ConsumableSmall_Athena_C
{
public:
	class FName                                   NewVar_0;                                          // 0x0928(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   NewVar_1;                                          // 0x0930(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   NewVar_2;                                          // 0x0938(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_ShadowBomb_Athena_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_ShadowBomb_Athena_C")
	}
	static class AB_ShadowBomb_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_ShadowBomb_Athena_C>();
	}
};
DUMPER7_ASSERTS_AB_ShadowBomb_Athena_C;

}

