#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BattleMapPawn

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BattleMapPawn.BP_BattleMapPawn_C
// 0x0000 (0x0410 - 0x0410)
class ABP_BattleMapPawn_C final : public ABattleMapPawn
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BattleMapPawn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BattleMapPawn_C")
	}
	static class ABP_BattleMapPawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BattleMapPawn_C>();
	}
};
DUMPER7_ASSERTS_ABP_BattleMapPawn_C;

}

