#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CameraLens_IceFrost

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CameraLens_IceFrost.BP_CameraLens_IceFrost_C
// 0x0000 (0x0300 - 0x0300)
class ABP_CameraLens_IceFrost_C final : public AEmitterCameraLensEffectBase
{
public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CameraLens_IceFrost_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CameraLens_IceFrost_C")
	}
	static class ABP_CameraLens_IceFrost_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CameraLens_IceFrost_C>();
	}
};
DUMPER7_ASSERTS_ABP_CameraLens_IceFrost_C;

}

