#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PoisonDartTrap_Wall

#include "Basic.hpp"

#include "BP_PoisonDartTrap_Floor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PoisonDartTrap_Wall.BP_PoisonDartTrap_Wall_C
// 0x0000 (0x0CD8 - 0x0CD8)
class ABP_PoisonDartTrap_Wall_C final : public ABP_PoisonDartTrap_Floor_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PoisonDartTrap_Wall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PoisonDartTrap_Wall_C")
	}
	static class ABP_PoisonDartTrap_Wall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PoisonDartTrap_Wall_C>();
	}
};
DUMPER7_ASSERTS_ABP_PoisonDartTrap_Wall_C;

}

