#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpectatorPC

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SpectatorPC.BP_SpectatorPC_C
// 0x0010 (0x2948 - 0x2938)
class ABP_SpectatorPC_C final : public AFortPlayerControllerSpectating
{
public:
	uint8                                         Pad_2938[0x8];                                     // 0x2938(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x2940(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_SpectatorPC(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SpectatorPC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SpectatorPC_C")
	}
	static class ABP_SpectatorPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SpectatorPC_C>();
	}
};
DUMPER7_ASSERTS_ABP_SpectatorPC_C;

}

