#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SolarisPrototype

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SolarisPrototype.BP_SolarisPrototype_C
// 0x0008 (0x0248 - 0x0240)
class ABP_SolarisPrototype_C final : public ASolarisPrototype
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	struct FSolarisResponse CheckEndConditions();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SolarisPrototype_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SolarisPrototype_C")
	}
	static class ABP_SolarisPrototype_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SolarisPrototype_C>();
	}
};
DUMPER7_ASSERTS_ABP_SolarisPrototype_C;

}

