#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_MobileCloseXHamburgerMenu

#include "Basic.hpp"

#include "ButtonStyle_MediumTransparentNoCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle_MobileCloseXHamburgerMenu.ButtonStyle_MobileCloseXHamburgerMenu_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyle_MobileCloseXHamburgerMenu_C final : public UButtonStyle_MediumTransparentNoCues_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ButtonStyle_MobileCloseXHamburgerMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ButtonStyle_MobileCloseXHamburgerMenu_C")
	}
	static class UButtonStyle_MobileCloseXHamburgerMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_MobileCloseXHamburgerMenu_C>();
	}
};
DUMPER7_ASSERTS_UButtonStyle_MobileCloseXHamburgerMenu_C;

}

