#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CamShake_Shadow_Bomb

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CamShake_Shadow_Bomb.CamShake_Shadow_Bomb_C
// 0x0000 (0x0160 - 0x0160)
class UCamShake_Shadow_Bomb_C final : public UCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CamShake_Shadow_Bomb_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CamShake_Shadow_Bomb_C")
	}
	static class UCamShake_Shadow_Bomb_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCamShake_Shadow_Bomb_C>();
	}
};
DUMPER7_ASSERTS_UCamShake_Shadow_Bomb_C;

}

