#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CandleSingle

#include "Basic.hpp"

#include "Parent_BuildingPropActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CandleSingle.CandleSingle_C
// 0x0010 (0x0BF0 - 0x0BE0)
class ACandleSingle_C final : public AParent_BuildingPropActor_C
{
public:
	class UStaticMeshComponent*                   SM_FlameShape;                                     // 0x0BE0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x0BE8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CandleSingle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CandleSingle_C")
	}
	static class ACandleSingle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACandleSingle_C>();
	}
};
DUMPER7_ASSERTS_ACandleSingle_C;

}

