#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChallengeProgressDisplay

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChallengeProgressDisplay.ChallengeProgressDisplay_C
// 0x0000 (0x0240 - 0x0240)
class UChallengeProgressDisplay_C final : public UAthenaChallengeProgressBar
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ChallengeProgressDisplay_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ChallengeProgressDisplay_C")
	}
	static class UChallengeProgressDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallengeProgressDisplay_C>();
	}
};
DUMPER7_ASSERTS_UChallengeProgressDisplay_C;

}

