#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChallengeInfoPanel

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChallengeInfoPanel.ChallengeInfoPanel_C
// 0x0000 (0x0290 - 0x0290)
class UChallengeInfoPanel_C final : public UAthenaChallengeInfoPanel
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ChallengeInfoPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ChallengeInfoPanel_C")
	}
	static class UChallengeInfoPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallengeInfoPanel_C>();
	}
};
DUMPER7_ASSERTS_UChallengeInfoPanel_C;

}

