#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CheckFeatureUnlockAction

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass CheckFeatureUnlockAction.CheckFeatureUnlockAction_C
// 0x0010 (0x02B0 - 0x02A0)
class ACheckFeatureUnlockAction_C final : public AFortScriptedAction
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void IsFeatureUnlockRunning(bool* bRunning);
	void IsFrontendDailyRewardsRunning(bool* IsRunning);
	void ShowFeatureUnlock();
	void IsFeatureUnlockAvailable(bool* Feature_Unlock_Available);
	void IsFrontEndRewardsRunning(bool* bRunning);
	void Execute(const struct FFortScriptedActionParams& Params_0);
	void ExecuteUbergraph_CheckFeatureUnlockAction(int32 EntryPoint);
	void HandleFeatureUnlockClosed();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CheckFeatureUnlockAction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CheckFeatureUnlockAction_C")
	}
	static class ACheckFeatureUnlockAction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACheckFeatureUnlockAction_C>();
	}
};
DUMPER7_ASSERTS_ACheckFeatureUnlockAction_C;

}

