#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CheckForUnfloweringUITutorials

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass CheckForUnfloweringUITutorials.CheckForUnfloweringUITutorials_C
// 0x0010 (0x02B0 - 0x02A0)
class ACheckForUnfloweringUITutorials_C final : public AFortScriptedAction
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void CanRunTutorialQuests(bool* Result);
	void Execute(const struct FFortScriptedActionParams& Params_0);
	void ExecuteUbergraph_CheckForUnfloweringUITutorials(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CheckForUnfloweringUITutorials_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CheckForUnfloweringUITutorials_C")
	}
	static class ACheckForUnfloweringUITutorials_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACheckForUnfloweringUITutorials_C>();
	}
};
DUMPER7_ASSERTS_ACheckForUnfloweringUITutorials_C;

}

