#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CheckFrontEndDailyRewardsAction

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"
#include "FortniteUI_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass CheckFrontEndDailyRewardsAction.CheckFrontEndDailyRewardsAction_C
// 0x0018 (0x02B8 - 0x02A0)
class ACheckFrontEndDailyRewardsAction_C final : public AFortScriptedAction
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          bLastStateWasLoginScreen;                          // 0x02B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_CheckFrontEndDailyRewardsAction(int32 EntryPoint);
	void HandleClientEvent_FinishedModalQueue(class UObject* EventSource, class UObject* EventFocus, const struct FFortClientEvent& ClientEvent);
	void Execute(const struct FFortScriptedActionParams& Params_0);
	void ShowDailyRewards();
	void CompleteDailyRewardAction();
	void Daily_Rewards_Open(bool* bRunning);
	void IsFrontEndRewards_Running(bool* IsRunning);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CheckFrontEndDailyRewardsAction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CheckFrontEndDailyRewardsAction_C")
	}
	static class ACheckFrontEndDailyRewardsAction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACheckFrontEndDailyRewardsAction_C>();
	}
};
DUMPER7_ASSERTS_ACheckFrontEndDailyRewardsAction_C;

}

