#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ConstructorMannequin_Female

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ConstructorMannequin_Female.ConstructorMannequin_Female_C
// 0x0000 (0x0478 - 0x0478)
class AConstructorMannequin_Female_C final : public AFortPlayerMannequin
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ConstructorMannequin_Female_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ConstructorMannequin_Female_C")
	}
	static class AConstructorMannequin_Female_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AConstructorMannequin_Female_C>();
	}
};
DUMPER7_ASSERTS_AConstructorMannequin_Female_C;

}

