#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Creative_Powerup_Grind

#include "Basic.hpp"

#include "Creative_Powerup_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Creative_Powerup_Grind.Creative_Powerup_Grind_C
// 0x0008 (0x0778 - 0x0770)
class ACreative_Powerup_Grind_C final : public ACreative_Powerup_C
{
public:
	bool                                          ShouldShowGrindEffect;                             // 0x0770(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void SetupEffectData(const struct FGameplayEffectSpecHandle& EffectHandle, struct FGameplayEffectSpecHandle* OutEffectHandle);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Creative_Powerup_Grind_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Creative_Powerup_Grind_C")
	}
	static class ACreative_Powerup_Grind_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACreative_Powerup_Grind_C>();
	}
};
DUMPER7_ASSERTS_ACreative_Powerup_Grind_C;

}

