#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FriendCodeFrontEndShareButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FriendCodeFrontEndShareButton.FriendCodeFrontEndShareButton_C
// 0x0008 (0x0B88 - 0x0B80)
class UFriendCodeFrontEndShareButton_C final : public UFriendCodeShareButtonBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0B80(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void Construct();
	void BP_OnClicked();
	void ExecuteUbergraph_FriendCodeFrontEndShareButton(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FriendCodeFrontEndShareButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FriendCodeFrontEndShareButton_C")
	}
	static class UFriendCodeFrontEndShareButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFriendCodeFrontEndShareButton_C>();
	}
};
DUMPER7_ASSERTS_UFriendCodeFrontEndShareButton_C;

}

