#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Frontend_Research

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Frontend_Research.Frontend_Research_C
// 0x0000 (0x0258 - 0x0258)
class AFrontend_Research_C final : public AFortLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Frontend_Research_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Frontend_Research_C")
	}
	static class AFrontend_Research_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFrontend_Research_C>();
	}
};
DUMPER7_ASSERTS_AFrontend_Research_C;

}

