#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FrontEndStore_Pinata

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FrontEndStore_Pinata.FrontEndStore_Pinata_C
// 0x0000 (0x0258 - 0x0258)
class AFrontEndStore_Pinata_C final : public AFortLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FrontEndStore_Pinata_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FrontEndStore_Pinata_C")
	}
	static class AFrontEndStore_Pinata_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFrontEndStore_Pinata_C>();
	}
};
DUMPER7_ASSERTS_AFrontEndStore_Pinata_C;

}

