#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_IceGrenade

#include "Basic.hpp"

#include "GA_ThrowConsumable_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_IceGrenade.GA_Athena_IceGrenade_C
// 0x0000 (0x0AB8 - 0x0AB8)
class UGA_Athena_IceGrenade_C final : public UGA_ThrowConsumable_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Athena_IceGrenade_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Athena_IceGrenade_C")
	}
	static class UGA_Athena_IceGrenade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_IceGrenade_C>();
	}
};
DUMPER7_ASSERTS_UGA_Athena_IceGrenade_C;

}

