#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Creative_Powerup_Grind

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Creative_Powerup_Grind.GA_Creative_Powerup_Grind_C
// 0x0018 (0x0958 - 0x0940)
class UGA_Creative_Powerup_Grind_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0940(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UClass*                                 GameplayEffectClass;                               // 0x0948(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 TargetActor;                                       // 0x0950(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Creative_Powerup_Grind(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Creative_Powerup_Grind_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Creative_Powerup_Grind_C")
	}
	static class UGA_Creative_Powerup_Grind_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Creative_Powerup_Grind_C>();
	}
};
DUMPER7_ASSERTS_UGA_Creative_Powerup_Grind_C;

}

