#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_CP_Standalone_L_TomatoTemple_a

#include "Basic.hpp"

#include "GA_Athena_Instance_PlaysetGrenadeWithTrajectory_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_CP_Standalone_L_TomatoTemple_a.GA_CP_Standalone_L_TomatoTemple_a_C
// 0x0000 (0x0C90 - 0x0C90)
class UGA_CP_Standalone_L_TomatoTemple_a_C final : public UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_CP_Standalone_L_TomatoTemple_a_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_CP_Standalone_L_TomatoTemple_a_C")
	}
	static class UGA_CP_Standalone_L_TomatoTemple_a_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_CP_Standalone_L_TomatoTemple_a_C>();
	}
};
DUMPER7_ASSERTS_UGA_CP_Standalone_L_TomatoTemple_a_C;

}

