#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Perk_H_FullyContained_DamageOnHit

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "GAT_GenericTriggeredAbility_Perk_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Perk_H_FullyContained_DamageOnHit.GA_Perk_H_FullyContained_DamageOnHit_C
// 0x0010 (0x0A90 - 0x0A80)
class UGA_Perk_H_FullyContained_DamageOnHit_C final : public UGAT_GenericTriggeredAbility_Perk_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Perk_H_FullyContained_DamageOnHit_C; // 0x0A80(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTag                           Request_Reflection_Tag;                            // 0x0A88(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Perk_H_FullyContained_DamageOnHit(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Perk_H_FullyContained_DamageOnHit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Perk_H_FullyContained_DamageOnHit_C")
	}
	static class UGA_Perk_H_FullyContained_DamageOnHit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Perk_H_FullyContained_DamageOnHit_C>();
	}
};
DUMPER7_ASSERTS_UGA_Perk_H_FullyContained_DamageOnHit_C;

}

