#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Trap_FloorFreeze_Athena

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "Engine_structs.hpp"
#include "GA_TrapGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Trap_FloorFreeze_Athena.GA_Trap_FloorFreeze_Athena_C
// 0x0040 (0x09B0 - 0x0970)
class UGA_Trap_FloorFreeze_Athena_C : public UGA_TrapGeneric_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Trap_FloorFreeze_Athena_C;       // 0x0970(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FFortTargetFilter                      TargetFilter;                                      // 0x0978(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_GA_Trap_FloorFreeze_Athena(int32 EntryPoint);
	void Cancelled_4882FEAA4B32D70FE53C06A619E266D1(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void GA_LifeTimer();
	void Targeted_4882FEAA4B32D70FE53C06A619E266D1(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Trap_FloorFreeze_Athena_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Trap_FloorFreeze_Athena_C")
	}
	static class UGA_Trap_FloorFreeze_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Trap_FloorFreeze_Athena_C>();
	}
};
DUMPER7_ASSERTS_UGA_Trap_FloorFreeze_Athena_C;

}

