#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Garage_Door_03

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Garage_Door_03.Garage_Door_03_C
// 0x0000 (0x0B10 - 0x0B10)
class AGarage_Door_03_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Garage_Door_03_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Garage_Door_03_C")
	}
	static class AGarage_Door_03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGarage_Door_03_C>();
	}
};
DUMPER7_ASSERTS_AGarage_Door_03_C;

}

