#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCL_ToxicDingo

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCL_ToxicDingo.GCL_ToxicDingo_C
// 0x0000 (0x0790 - 0x0790)
class AGCL_ToxicDingo_C final : public AFortGameplayCueNotify_Loop
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCL_ToxicDingo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCL_ToxicDingo_C")
	}
	static class AGCL_ToxicDingo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCL_ToxicDingo_C>();
	}
};
DUMPER7_ASSERTS_AGCL_ToxicDingo_C;

}

