#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Vehicle_Baller_Impact

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_Vehicle_Baller_Impact.GCN_Vehicle_Baller_Impact_C
// 0x0000 (0x01A0 - 0x01A0)
class UGCN_Vehicle_Baller_Impact_C final : public UFortGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_Vehicle_Baller_Impact_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_Vehicle_Baller_Impact_C")
	}
	static class UGCN_Vehicle_Baller_Impact_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_Vehicle_Baller_Impact_C>();
	}
};
DUMPER7_ASSERTS_UGCN_Vehicle_Baller_Impact_C;

}

