#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Athena_Balloons_Consumable_QuestCheck

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Athena_Balloons_Consumable_QuestCheck.GE_Athena_Balloons_Consumable_QuestCheck_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_Athena_Balloons_Consumable_QuestCheck_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Athena_Balloons_Consumable_QuestCheck_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Athena_Balloons_Consumable_QuestCheck_C")
	}
	static class UGE_Athena_Balloons_Consumable_QuestCheck_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Athena_Balloons_Consumable_QuestCheck_C>();
	}
};
DUMPER7_ASSERTS_UGE_Athena_Balloons_Consumable_QuestCheck_C;

}

