#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Perk_C_Constructor_BASE_DefaultBuff

#include "Basic.hpp"

#include "GET_TagContainer_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Perk_C_Constructor_BASE_DefaultBuff.GE_Perk_C_Constructor_BASE_DefaultBuff_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_Perk_C_Constructor_BASE_DefaultBuff_C final : public UGET_TagContainer_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Perk_C_Constructor_BASE_DefaultBuff_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Perk_C_Constructor_BASE_DefaultBuff_C")
	}
	static class UGE_Perk_C_Constructor_BASE_DefaultBuff_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Perk_C_Constructor_BASE_DefaultBuff_C>();
	}
};
DUMPER7_ASSERTS_UGE_Perk_C_Constructor_BASE_DefaultBuff_C;

}

