#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_ShadowBOmbLoop

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_ShadowBOmbLoop.GE_ShadowBombLoop_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_ShadowBombLoop_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_ShadowBombLoop_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_ShadowBombLoop_C")
	}
	static class UGE_ShadowBombLoop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_ShadowBombLoop_C>();
	}
};
DUMPER7_ASSERTS_UGE_ShadowBombLoop_C;

}

