#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GET_DirectBluntDamage

#include "Basic.hpp"

#include "GET_DirectPhysicalDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GET_DirectBluntDamage.GET_DirectBluntDamage_C
// 0x0000 (0x05F0 - 0x05F0)
class UGET_DirectBluntDamage_C : public UGET_DirectPhysicalDamage_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GET_DirectBluntDamage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GET_DirectBluntDamage_C")
	}
	static class UGET_DirectBluntDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGET_DirectBluntDamage_C>();
	}
};
DUMPER7_ASSERTS_UGET_DirectBluntDamage_C;

}

