#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HoloScreen

#include "Basic.hpp"

#include "HoloScreen_classes.hpp"
#include "HoloScreen_parameters.hpp"


namespace SDK
{

// Function HoloScreen.HoloScreen_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AHoloScreen_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HoloScreen_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

