#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hospital_MountedTV

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Hospital_MountedTV.Hospital_MountedTV_C
// 0x0000 (0x0B10 - 0x0B10)
class AHospital_MountedTV_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Hospital_MountedTV_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Hospital_MountedTV_C")
	}
	static class AHospital_MountedTV_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHospital_MountedTV_C>();
	}
};
DUMPER7_ASSERTS_AHospital_MountedTV_C;

}

