#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lobby

#include "Basic.hpp"

#include "Lobby_structs.hpp"
#include "OnlineSubsystemUtils_classes.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class Lobby.LobbyBeaconClient
// 0x0088 (0x0348 - 0x02C0)
class ALobbyBeaconClient : public AOnlineBeaconClient
{
public:
	class ALobbyBeaconState*                      LobbyState;                                        // 0x02C0(0x0008)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ALobbyBeaconPlayerState*                PlayerState;                                       // 0x02C8(0x0008)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2D0[0x1];                                      // 0x02D0(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	ELobbyBeaconJoinState                         LobbyJoinServerState;                              // 0x02D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2D2[0x76];                                     // 0x02D2(0x0076)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ClientAckJoiningServer();
	void ClientJoinGame();
	void ClientLoginComplete(const struct FUniqueNetIdRepl& InUniqueId, bool bWasSuccessful);
	void ClientPlayerJoined(const class FText& NewPlayerName, const struct FUniqueNetIdRepl& InUniqueId);
	void ClientPlayerLeft(const struct FUniqueNetIdRepl& InUniqueId);
	void ClientSetInviteFlags(const struct FJoinabilitySettings& Settings);
	void ClientWasKicked(const class FText& KickReason);
	void ServerCheat(const class FString& Msg);
	void ServerDisconnectFromLobby();
	void ServerKickPlayer(const struct FUniqueNetIdRepl& PlayerToKick, const class FText& Reason);
	void ServerLoginPlayer(const class FString& InSessionId, const struct FUniqueNetIdRepl& InUniqueId, const class FString& UrlString);
	void ServerNotifyJoiningServer();
	void ServerSetPartyOwner(const struct FUniqueNetIdRepl& InUniqueId, const struct FUniqueNetIdRepl& InPartyOwnerId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LobbyBeaconClient")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LobbyBeaconClient")
	}
	static class ALobbyBeaconClient* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALobbyBeaconClient>();
	}
};
DUMPER7_ASSERTS_ALobbyBeaconClient;

// Class Lobby.LobbyBeaconHost
// 0x0038 (0x02A0 - 0x0268)
class ALobbyBeaconHost : public AOnlineBeaconHostObject
{
public:
	uint8                                         Pad_268[0x8];                                      // 0x0268(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftClassPtr<class UClass>                   LobbyStateClass;                                   // 0x0270(0x0028)(Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class ALobbyBeaconState*                      LobbyState;                                        // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LobbyBeaconHost")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LobbyBeaconHost")
	}
	static class ALobbyBeaconHost* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALobbyBeaconHost>();
	}
};
DUMPER7_ASSERTS_ALobbyBeaconHost;

// Class Lobby.LobbyBeaconPlayerState
// 0x00C0 (0x0300 - 0x0240)
class ALobbyBeaconPlayerState : public AInfo
{
public:
	class FText                                   DisplayName;                                       // 0x0240(0x0018)(Net, NativeAccessSpecifierPublic)
	struct FUniqueNetIdRepl                       UniqueId;                                          // 0x0258(0x0028)(Net, RepNotify, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FUniqueNetIdRepl                       PartyOwnerUniqueId;                                // 0x0280(0x0028)(Net, RepNotify, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInLobby;                                          // 0x02A8(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2A9[0x7];                                      // 0x02A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AOnlineBeaconClient*                    ClientActor;                                       // 0x02B0(0x0008)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2B8[0x48];                                     // 0x02B8(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnRep_InLobby();
	void OnRep_PartyOwner();
	void OnRep_UniqueId();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LobbyBeaconPlayerState")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LobbyBeaconPlayerState")
	}
	static class ALobbyBeaconPlayerState* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALobbyBeaconPlayerState>();
	}
};
DUMPER7_ASSERTS_ALobbyBeaconPlayerState;

// Class Lobby.LobbyBeaconState
// 0x01A8 (0x03E8 - 0x0240)
class ALobbyBeaconState : public AInfo
{
public:
	int32                                         MaxPlayers;                                        // 0x0240(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_244[0x4];                                      // 0x0244(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class ALobbyBeaconPlayerState>    LobbyBeaconPlayerStateClass;                       // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_250[0x8];                                      // 0x0250(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bLobbyStarted;                                     // 0x0258(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_259[0x3];                                      // 0x0259(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         WaitForPlayersTimeRemaining;                       // 0x025C(0x0004)(Net, ZeroConstructor, Config, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FLobbyPlayerStateInfoArray             Players;                                           // 0x0260(0x0120)(Net, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_380[0x68];                                     // 0x0380(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnRep_LobbyStarted();
	void OnRep_WaitForPlayersTimeRemaining();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LobbyBeaconState")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LobbyBeaconState")
	}
	static class ALobbyBeaconState* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALobbyBeaconState>();
	}
};
DUMPER7_ASSERTS_ALobbyBeaconState;

}

