#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoveStorm_MenuMap

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass LoveStorm_MenuMap.LoveStorm_MenuMap_C
// 0x0010 (0x0268 - 0x0258)
class ALoveStorm_MenuMap_C final : public AFortLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0258(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ASoldierMannequin_Male_C*               hr0010DarkCupid_ExecuteUbergraph_LoveStorm_MenuMap_RefProperty; // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_LoveStorm_MenuMap(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LoveStorm_MenuMap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LoveStorm_MenuMap_C")
	}
	static class ALoveStorm_MenuMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALoveStorm_MenuMap_C>();
	}
};
DUMPER7_ASSERTS_ALoveStorm_MenuMap_C;

}

