#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NeoTilted_Planter_Rectangle

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NeoTilted_Planter_Rectangle.NeoTilted_Planter_Rectangle_C
// 0x0000 (0x0B10 - 0x0B10)
class ANeoTilted_Planter_Rectangle_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NeoTilted_Planter_Rectangle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NeoTilted_Planter_Rectangle_C")
	}
	static class ANeoTilted_Planter_Rectangle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANeoTilted_Planter_Rectangle_C>();
	}
};
DUMPER7_ASSERTS_ANeoTilted_Planter_Rectangle_C;

}

