#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NeoTilted_BusStop

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NeoTilted_BusStop.NeoTilted_BusStop_C
// 0x0000 (0x0B10 - 0x0B10)
class ANeoTilted_BusStop_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NeoTilted_BusStop_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NeoTilted_BusStop_C")
	}
	static class ANeoTilted_BusStop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANeoTilted_BusStop_C>();
	}
};
DUMPER7_ASSERTS_ANeoTilted_BusStop_C;

}

