#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NeoTilted_TrashCan

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NeoTilted_TrashCan.NeoTilted_TrashCan_C
// 0x0000 (0x0B10 - 0x0B10)
class ANeoTilted_TrashCan_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NeoTilted_TrashCan_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NeoTilted_TrashCan_C")
	}
	static class ANeoTilted_TrashCan_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANeoTilted_TrashCan_C>();
	}
};
DUMPER7_ASSERTS_ANeoTilted_TrashCan_C;

}

