#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_Durr_Mascot

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Prop_Durr_Mascot.Prop_Durr_Mascot_C
// 0x0000 (0x0B10 - 0x0B10)
class AProp_Durr_Mascot_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Prop_Durr_Mascot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Prop_Durr_Mascot_C")
	}
	static class AProp_Durr_Mascot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_Durr_Mascot_C>();
	}
};
DUMPER7_ASSERTS_AProp_Durr_Mascot_C;

}

