#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sign_Exit_Leave

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Sign_Exit_Leave.Sign_Exit_Leave_C
// 0x0000 (0x0B10 - 0x0B10)
class ASign_Exit_Leave_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Sign_Exit_Leave_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Sign_Exit_Leave_C")
	}
	static class ASign_Exit_Leave_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASign_Exit_Leave_C>();
	}
};
DUMPER7_ASSERTS_ASign_Exit_Leave_C;

}

