#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tiered_BluGlo_Parent

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tiered_BluGlo_Parent.Tiered_BluGlo_Parent_C
// 0x0008 (0x0C58 - 0x0C50)
class ATiered_BluGlo_Parent_C final : public ABuildingContainer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0C50(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Tiered_BluGlo_Parent(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Tiered_BluGlo_Parent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Tiered_BluGlo_Parent_C")
	}
	static class ATiered_BluGlo_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATiered_BluGlo_Parent_C>();
	}
};
DUMPER7_ASSERTS_ATiered_BluGlo_Parent_C;

}

