#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tree_Bush_1a

#include "Basic.hpp"

#include "Parent_Tree_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tree_Bush_1a.Tree_Bush_1a_C
// 0x0000 (0x0BD0 - 0x0BD0)
class ATree_Bush_1a_C final : public AParent_Tree_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Tree_Bush_1a_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Tree_Bush_1a_C")
	}
	static class ATree_Bush_1a_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATree_Bush_1a_C>();
	}
};
DUMPER7_ASSERTS_ATree_Bush_1a_C;

}

