#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UACBase

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class UACBase.UACNetworkComponent
// 0x0100 (0x01D8 - 0x00D8)
class UUACNetworkComponent final : public UActorComponent
{
public:
	int32                                         PlayerID;                                          // 0x00D8(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_DC[0xFC];                                      // 0x00DC(0x00FC)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SendClientHello(uint32 SessionKey);
	void SendPacketToClient(uint8 Type, const TArray<uint8>& Packet);
	void SendPacketToServer(uint8 Type, const TArray<uint8>& Packet);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UACNetworkComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UACNetworkComponent")
	}
	static class UUACNetworkComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUACNetworkComponent>();
	}
};
DUMPER7_ASSERTS_UUACNetworkComponent;

}

